package org.geppetto.domain;

public enum Operator {
   UNARY_PLUS, UNARY_MINUS, UNARY_NEGATION, MULTIPLY, DIVIDE, MODULUS, ADD, SUBTRACT, GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN, LESS_THAN_OR_EQUAL_TO, EQUAL_TO, NOT_EQUAL_TO, LOGICAL_AND, LOGICAL_OR, ASSIGNMENT;
}
